/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectgameon.gui;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import projectgameon.Player.Personagem;
import projectgameon.Player.Player;
/**
 *
 * @author aluno
 */
public class Combate extends javax.swing.JFrame {

    Personagem personagem;
    Player playerData;
    
    /**
     * Creates new form Combate
     */
    public Combate(Personagem personagem , Player playerData) {
        initComponents();
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        this.personagem = personagem;        
        this.playerData = playerData;
        icon();
    }
    
    public void icon(){
        
        ImageIcon myImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/projectgameon/gui/images/backgrounds/bg_combate.jpg")));
        Image im = myImage.getImage();
        Image im2 = im.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(im2);
        jLabel1.setIcon(icon);
        
        if(personagem.getClasse().equals("mago")){
            myImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/projectgameon/gui/images/sprites/Classes/Mago.png")));
        }else if(personagem.getClasse().equals("guerreiro")){
            myImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/projectgameon/gui/images/sprites/Classes/Guerreiro.png")));
        }else if(personagem.getClasse().equals("arqueiro")){
            myImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/projectgameon/gui/images/sprites/Classes/Arqueiro.png")));
        }
        
        im = myImage.getImage();
        im2 = im.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(im2);
        jLabel3.setIcon(icon);
        
        laInimigo1.setText(personagem.getNome() +" Level:"+ personagem.getLvl());
        pbVidaJogador.setMaximum(personagem.getHptotal());
        pbVidaJogador.setValue(personagem.getHpatual());

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laInimigo2 = new javax.swing.JLabel();
        laInimigo1 = new javax.swing.JLabel();
        laInimigo3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pbVidaJogador = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        imageInimigo1 = new javax.swing.JLabel();
        imageInimigo2 = new javax.swing.JLabel();
        lIconeVida = new javax.swing.JLabel();
        pbVidaJogador1 = new javax.swing.JProgressBar();
        pbVidaJogador2 = new javax.swing.JProgressBar();
        lIconeVida4 = new javax.swing.JLabel();
        bItens = new javax.swing.JButton();
        bFugir = new javax.swing.JButton();
        bAtacar = new javax.swing.JButton();
        bHabilidades = new javax.swing.JButton();
        LogJogador = new javax.swing.JLabel();
        lIconeVida2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IF QUEST - COMBATE!");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        laInimigo2.setText("(Aqui vem o Tipo de monstro e seu nível)");
        getContentPane().add(laInimigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1217, 79, 300, 62));

        laInimigo1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        laInimigo1.setForeground(new java.awt.Color(1, 1, 1));
        laInimigo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laInimigo1.setText("(Aqui vem o nome do jogador e seu nível)");
        getContentPane().add(laInimigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 145, 300, 62));

        laInimigo3.setText("(Aqui vem o Tipo de monstro e seu nível)");
        getContentPane().add(laInimigo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 79, 300, 62));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 213, 255, 255));

        pbVidaJogador.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(pbVidaJogador, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 53, 250, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 270, 260));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 220, 270, 250));
        getContentPane().add(imageInimigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 213, 255, 255));
        getContentPane().add(imageInimigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1262, 213, 255, 255));

        lIconeVida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgameon/gui/img/Coraçãozinho de Vida 2.0.png"))); // NOI18N
        getContentPane().add(lIconeVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 46, -1, -1));
        getContentPane().add(pbVidaJogador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 53, 250, -1));
        getContentPane().add(pbVidaJogador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1267, 53, 250, -1));

        lIconeVida4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgameon/gui/img/Coraçãozinho de Vida 2.0.png"))); // NOI18N
        getContentPane().add(lIconeVida4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1224, 46, -1, -1));

        bItens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgameon/gui/img/button_itens.png"))); // NOI18N
        getContentPane().add(bItens, new org.netbeans.lib.awtextra.AbsoluteConstraints(1418, 509, 145, 40));

        bFugir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgameon/gui/img/button_fugir.png"))); // NOI18N
        bFugir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFugirActionPerformed(evt);
            }
        });
        getContentPane().add(bFugir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1418, 587, 145, 40));

        bAtacar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgameon/gui/img/button_atacar.png"))); // NOI18N
        bAtacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtacarActionPerformed(evt);
            }
        });
        getContentPane().add(bAtacar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1156, 509, 140, 40));

        bHabilidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgameon/gui/img/button_habilidades.png"))); // NOI18N
        getContentPane().add(bHabilidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(1156, 587, 140, 40));

        LogJogador.setText("Aqui vai todo log de informações que o jogador deve saber como \"Escolha sua ação\" ou \"Seu ataque deu x de dano\"");
        LogJogador.setToolTipText("");
        getContentPane().add(LogJogador, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 509, 708, 70));

        lIconeVida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgameon/gui/img/Coraçãozinho de Vida 2.0.png"))); // NOI18N
        getContentPane().add(lIconeVida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 46, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1595, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bFugirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFugirActionPerformed
        new Inventario(playerData, personagem).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bFugirActionPerformed

    private void bAtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtacarActionPerformed
        //if(personagem.getClasse().equals("mago")){
            
            
        //}
    }//GEN-LAST:event_bAtacarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogJogador;
    private javax.swing.JButton bAtacar;
    private javax.swing.JButton bFugir;
    private javax.swing.JButton bHabilidades;
    private javax.swing.JButton bItens;
    private javax.swing.JLabel imageInimigo1;
    private javax.swing.JLabel imageInimigo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lIconeVida;
    private javax.swing.JLabel lIconeVida2;
    private javax.swing.JLabel lIconeVida4;
    private javax.swing.JLabel laInimigo1;
    private javax.swing.JLabel laInimigo2;
    private javax.swing.JLabel laInimigo3;
    private javax.swing.JProgressBar pbVidaJogador;
    private javax.swing.JProgressBar pbVidaJogador1;
    private javax.swing.JProgressBar pbVidaJogador2;
    // End of variables declaration//GEN-END:variables
}
