/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectgameon.gui;

import Config.JDBC;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import projectgameon.Player.Player;

/**
 *
 * @author aluno
 */
public final class MenuPrincipal extends javax.swing.JFrame {
    
    Player playerData;
    
    /**
     * Creates new form MenuPrincipal
     * @param playerData
     */
    public MenuPrincipal(Player playerData) {
        initComponents();
        loadGraph();
        this.playerData = playerData;
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    public void loadGraph(){
        ImageIcon myImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/projectgameon/gui/img/bg.jpg")));
        Image im = myImage.getImage();
        Image im2 = im.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(im2);
        jLabel1.setIcon(icon);
        System.out.println(bNovoJogo.getHeight()+"\n"+bNovoJogo.getWidth());
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lLogo = new javax.swing.JLabel();
        bNovoJogo = new javax.swing.JButton();
        bContinuar = new javax.swing.JButton();
        bSaves = new javax.swing.JButton();
        bSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IF QUEST");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgameon/gui/img/logo.png"))); // NOI18N
        lLogo.setText("(Place Holder do logo)");
        getContentPane().add(lLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 500, 150));

        bNovoJogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgameon/gui/img/button_novo-jogo.png"))); // NOI18N
        bNovoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNovoJogoActionPerformed(evt);
            }
        });
        getContentPane().add(bNovoJogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 190, 50));

        bContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgameon/gui/img/button_continuar.png"))); // NOI18N
        bContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(bContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 190, 50));

        bSaves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgameon/gui/img/button_saves.png"))); // NOI18N
        bSaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSavesActionPerformed(evt);
            }
        });
        getContentPane().add(bSaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 190, 50));

        bSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgameon/gui/img/button_sair.png"))); // NOI18N
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });
        getContentPane().add(bSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, 190, 50));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_bSairActionPerformed

    private void bNovoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNovoJogoActionPerformed
        new JDBC().Clear(this.playerData);
        new SelecaoPersonagem(this.playerData).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bNovoJogoActionPerformed

    private void bContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bContinuarActionPerformed
        new SelecaoPersonagem(this.playerData).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bContinuarActionPerformed

    private void bSavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSavesActionPerformed
        new SelecaoPersonagem(this.playerData).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bSavesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bContinuar;
    private javax.swing.JButton bNovoJogo;
    private javax.swing.JButton bSair;
    private javax.swing.JButton bSaves;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lLogo;
    // End of variables declaration//GEN-END:variables
}
