/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectgameon.gui;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import projectgameon.Player.Player;

public class SelecaoPersonagem extends javax.swing.JFrame {

    Player playerData;
    /**
     * Creates new form SelecaoPersonagem
     * @param playerData
     */
    public SelecaoPersonagem(Player playerData) {
        initComponents();
        loadGraph();
        this.playerData = playerData;
        loadValues();
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    public final void loadGraph(){
        ImageIcon myImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/projectgameon/gui/img/bg.jpg")));
        Image im = myImage.getImage();
        Image im2 = im.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(im2);
        jLabel5.setIcon(icon);
    }
    
    public void loadValues(){
        if(playerData.getPersonagemA().getNome() == null){
            
        }else{
            this.NomeSave1.setText(this.playerData.getPersonagemA().getNome());
            this.NivelSave1.setText(String.valueOf(this.playerData.getPersonagemA().getLvl()));
            this.ClasseSave1.setText(this.playerData.getPersonagemA().getClasse());            
        }
        
        if(playerData.getPersonagemB().getNome() == null){
        
        }else{
            this.NomeSave2.setText(this.playerData.getPersonagemB().getNome());
            this.NivelSave2.setText(String.valueOf(this.playerData.getPersonagemB().getLvl()));
            this.ClasseSave2.setText(this.playerData.getPersonagemB().getClasse());            
        }
        
        if(playerData.getPersonagemC().getNome() == null){
        
        }else{
            this.NomeSave3.setText(this.playerData.getPersonagemC().getNome());
            this.NivelSave3.setText(String.valueOf(this.playerData.getPersonagemC().getLvl()));
            this.ClasseSave3.setText(this.playerData.getPersonagemC().getClasse());            
        }        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NomeSave2 = new javax.swing.JTextField();
        NomeSave3 = new javax.swing.JTextField();
        NivelSave2 = new javax.swing.JTextField();
        NomeSave1 = new javax.swing.JTextField();
        NivelSave3 = new javax.swing.JTextField();
        ClasseSave1 = new javax.swing.JTextField();
        ClasseSave2 = new javax.swing.JTextField();
        ClasseSave3 = new javax.swing.JTextField();
        NivelSave1 = new javax.swing.JTextField();
        bJogarSave1 = new javax.swing.JButton();
        bJogarSave3 = new javax.swing.JButton();
        bJogarSave2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IF QUEST - Seleção de Personagem");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgameon/gui/img/button_continue-a-sua-aventura-de-onde-parou-selecione-o-personagem-que-queira-jogar.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgameon/gui/img/button_classe.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgameon/gui/img/button_nome.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgameon/gui/img/button_nivel.png"))); // NOI18N
        jLabel4.setToolTipText("");

        NomeSave2.setEditable(false);

        NomeSave3.setEditable(false);

        NivelSave2.setEditable(false);

        NomeSave1.setEditable(false);
        NomeSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeSave1ActionPerformed(evt);
            }
        });

        NivelSave3.setEditable(false);

        ClasseSave1.setEditable(false);

        ClasseSave2.setEditable(false);

        ClasseSave3.setEditable(false);

        NivelSave1.setEditable(false);

        bJogarSave1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bJogarSave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgameon/gui/img/button_jogar.png"))); // NOI18N
        bJogarSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJogarSave1ActionPerformed(evt);
            }
        });

        bJogarSave3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bJogarSave3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgameon/gui/img/button_jogar.png"))); // NOI18N
        bJogarSave3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJogarSave3ActionPerformed(evt);
            }
        });

        bJogarSave2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bJogarSave2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgameon/gui/img/button_jogar.png"))); // NOI18N
        bJogarSave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJogarSave2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeSave3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(NomeSave2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NomeSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(NivelSave2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NivelSave3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NivelSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClasseSave3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ClasseSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ClasseSave2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(165, 165, 165)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bJogarSave2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(bJogarSave3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bJogarSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))))
                    .addComponent(jLabel1))
                .addGap(81, 81, 81))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClasseSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NivelSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bJogarSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeSave2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NivelSave2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClasseSave2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bJogarSave2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeSave3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NivelSave3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClasseSave3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bJogarSave3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bJogarSave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJogarSave2ActionPerformed
        if(playerData.getPersonagemB().getNome() == null){
            new CriacaoPersonagem(this.playerData, "B").setVisible(true);
            this.setVisible(false);
        }else{
            System.out.println(playerData.getPersonagemB().getNome());
            new Inventario(playerData, playerData.getPersonagemB()).setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_bJogarSave2ActionPerformed

    private void bJogarSave3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJogarSave3ActionPerformed
        if(playerData.getPersonagemC().getNome() == null){
            new CriacaoPersonagem(this.playerData, "C").setVisible(true);
            this.setVisible(false);
        }else{
            System.out.println(playerData.getPersonagemC().getNome());
            new Inventario(playerData, playerData.getPersonagemC()).setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_bJogarSave3ActionPerformed

    private void bJogarSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJogarSave1ActionPerformed
        if(playerData.getPersonagemA().getNome() == null){
            new CriacaoPersonagem(this.playerData, "A").setVisible(true);
            this.setVisible(false);
        }else{
            System.out.println(playerData.getPersonagemA().getNome());
            new Inventario(playerData, playerData.getPersonagemA()).setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_bJogarSave1ActionPerformed

    private void NomeSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeSave1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeSave1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ClasseSave1;
    private javax.swing.JTextField ClasseSave2;
    private javax.swing.JTextField ClasseSave3;
    private javax.swing.JTextField NivelSave1;
    private javax.swing.JTextField NivelSave2;
    private javax.swing.JTextField NivelSave3;
    private javax.swing.JTextField NomeSave1;
    private javax.swing.JTextField NomeSave2;
    private javax.swing.JTextField NomeSave3;
    private javax.swing.JButton bJogarSave1;
    private javax.swing.JButton bJogarSave2;
    private javax.swing.JButton bJogarSave3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
